default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:password@localhost:5432/stock_api_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:password@localhost:5432/stock_api_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
